# Generated by Django 5.2.3 on 2025-06-30 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')]),
        ),
    ]
